/* ==========================================================
   QUOTE WALL — short, attributed lines of dialogue.
   Each entry is a brief quotation credited to its speaker and
   series. Kept deliberately short; full scripts belong to their
   rights holders.  { q, who, from, tag }
   ========================================================== */
const QUOTES = [
  { q: "I'm gonna be King of the Pirates!", who: "Monkey D. Luffy", from: "One Piece", tag: "Grit" },
  { q: "I never go back on my word.", who: "Naruto Uzumaki", from: "Naruto", tag: "Grit" },
  { q: "Set your heart ablaze.", who: "Kyojuro Rengoku", from: "Demon Slayer", tag: "Grit" },
  { q: "Go beyond. Plus Ultra!", who: "All Might", from: "My Hero Academia", tag: "Grit" },
  { q: "Fear is not evil. It tells you your weakness.", who: "Gildarts Clive", from: "Fairy Tail", tag: "Wisdom" },
  { q: "If you don't take risks, you can't create a future.", who: "Monkey D. Luffy", from: "One Piece", tag: "Wisdom" },
  { q: "A lesson without pain is meaningless.", who: "Edward Elric", from: "Fullmetal Alchemist: Brotherhood", tag: "Wisdom" },
  { q: "The world is not beautiful, therefore it is.", who: "Narrator", from: "Kino's Journey", tag: "Wisdom" },
  { q: "Whatever you lose, you'll find it again.", who: "Sōsuke Aizen", from: "Bleach", tag: "Wisdom" },
  { q: "Power comes in response to a need, not a desire.", who: "Son Goku", from: "Dragon Ball Z", tag: "Grit" },
  { q: "Hard work betrays none.", who: "Rock Lee", from: "Naruto", tag: "Grit" },
  { q: "People's lives don't end when they die.", who: "Itachi Uchiha", from: "Naruto", tag: "Loss" },
  { q: "A dropout will beat a genius through hard work.", who: "Rock Lee", from: "Naruto", tag: "Grit" },
  { q: "The moment you think of giving up, think of why you held on.", who: "Natsu Dragneel", from: "Fairy Tail", tag: "Grit" },
  { q: "Being weak is nothing to be ashamed of.", who: "Fuegoleon Vermillion", from: "Black Clover", tag: "Wisdom" },
  { q: "Fighting for your life and protecting someone are different.", who: "Levi Ackerman", from: "Attack on Titan", tag: "Battle" },
  { q: "If you win, you live. If you lose, you die.", who: "Eren Yeager", from: "Attack on Titan", tag: "Battle" },
  { q: "No matter how deep the night, it always turns to day.", who: "Brook", from: "One Piece", tag: "Hope" },
  { q: "The world isn't perfect. But it's there for us.", who: "Roy Mustang", from: "Fullmetal Alchemist: Brotherhood", tag: "Hope" },
  { q: "I'll take a potato chip — and eat it!", who: "Light Yagami", from: "Death Note", tag: "Chaos" },
  { q: "This world is rotten.", who: "Light Yagami", from: "Death Note", tag: "Chaos" },
  { q: "I am the hope of the universe.", who: "Son Goku", from: "Dragon Ball Z", tag: "Hope" },
  { q: "Talent blooms only through hard work.", who: "Kenma Kozume", from: "Haikyu!!", tag: "Sports" },
  { q: "Being the best decoy ever is so cool.", who: "Shoyo Hinata", from: "Haikyu!!", tag: "Sports" },
  { q: "The ball hasn't dropped yet.", who: "Yuu Nishinoya", from: "Haikyu!!", tag: "Sports" },
  { q: "Because I'm not alone anymore.", who: "Gon Freecss", from: "Hunter x Hunter", tag: "Bonds" },
  { q: "You should enjoy the little detours to the fullest.", who: "Ging Freecss", from: "Hunter x Hunter", tag: "Wisdom" },
  { q: "I refuse to let anyone else die.", who: "Yuji Itadori", from: "Jujutsu Kaisen", tag: "Bonds" },
  { q: "Throughout heaven and earth, I alone am the honored one.", who: "Satoru Gojo", from: "Jujutsu Kaisen", tag: "Chaos" },
  { q: "Nah, I'd win.", who: "Satoru Gojo", from: "Jujutsu Kaisen", tag: "Chaos" },
  { q: "Just because you're right doesn't mean you're not wrong.", who: "Vash the Stampede", from: "Trigun", tag: "Wisdom" },
  { q: "I am the bone of my sword.", who: "Archer", from: "Fate/stay night", tag: "Battle" },
  { q: "People die when they are killed.", who: "Shirou Emiya", from: "Fate/stay night", tag: "Chaos" },
  { q: "It's not the face that makes someone a monster.", who: "Ken Kaneki", from: "Tokyo Ghoul", tag: "Loss" },
  { q: "I'm not going to run away. I'll face them.", who: "Shinji Ikari", from: "Neon Genesis Evangelion", tag: "Grit" },
  { q: "Anywhere can be paradise as long as you have the will to live.", who: "Gintoki Sakata", from: "Gintama", tag: "Hope" },
  { q: "Don't live your life apologising.", who: "Gintoki Sakata", from: "Gintama", tag: "Wisdom" },
  { q: "Believe in the you that believes in yourself.", who: "Kamina", from: "Gurren Lagann", tag: "Grit" },
  { q: "Who the hell do you think I am?", who: "Kamina", from: "Gurren Lagann", tag: "Chaos" },
  { q: "Once you've lost something, you can never get it back.", who: "Homura Akemi", from: "Puella Magi Madoka Magica", tag: "Loss" },
  { q: "There is no shortcut to becoming strong.", who: "Saitama", from: "One Punch Man", tag: "Grit" },
  { q: "I'm just a guy who's a hero for fun.", who: "Saitama", from: "One Punch Man", tag: "Chaos" },
  { q: "Don't give up. There's no shame in falling down.", who: "Tanjiro Kamado", from: "Demon Slayer", tag: "Grit" },
  { q: "The bond between us can't be severed.", who: "Nezuko Kamado", from: "Demon Slayer", tag: "Bonds" },
  { q: "Whatever you do, do it with everything you have.", who: "Might Guy", from: "Naruto", tag: "Grit" },
  { q: "Thank you for loving me.", who: "Portgas D. Ace", from: "One Piece", tag: "Bonds" },
  { q: "Inherited will, destiny, dreams — these will never stop.", who: "Gol D. Roger", from: "One Piece", tag: "Hope" },
  { q: "Being lonely is worse than being hurt.", who: "Roronoa Zoro", from: "One Piece", tag: "Bonds" },
  { q: "Nothing can be gained without sacrificing something in return.", who: "Alphonse Elric", from: "Fullmetal Alchemist: Brotherhood", tag: "Wisdom" },
  { q: "Stand up and walk. You have strong legs.", who: "Edward Elric", from: "Fullmetal Alchemist: Brotherhood", tag: "Grit" },
  { q: "I want to be a person who can protect someone.", who: "Violet Evergarden", from: "Violet Evergarden", tag: "Bonds" },
  { q: "You can't stay in one place forever.", who: "Spike Spiegel", from: "Cowboy Bebop", tag: "Wisdom" },
  { q: "Whatever happens, happens.", who: "Spike Spiegel", from: "Cowboy Bebop", tag: "Wisdom" },
  { q: "Angels banished from heaven have no choice but to become devils.", who: "Vicious", from: "Cowboy Bebop", tag: "Loss" },
  { q: "Life is not a game of luck. To win, work hard.", who: "Sora", from: "No Game No Life", tag: "Grit" },
  { q: "It's okay to be weak. That's why we live together.", who: "Frieren", from: "Frieren: Beyond Journey's End", tag: "Bonds" },
  { q: "Ten years is a long time for humans.", who: "Frieren", from: "Frieren: Beyond Journey's End", tag: "Loss" },
  { q: "I have no dreams. I just want to fight.", who: "Denji", from: "Chainsaw Man", tag: "Chaos" },
  { q: "Losing your dream is worse than losing your life.", who: "Aki Hayakawa", from: "Chainsaw Man", tag: "Loss" },
  { q: "Even if I forget, the memory doesn't disappear.", who: "Mitsuha Miyamizu", from: "Your Name", tag: "Loss" },
  { q: "If you only look down, you'll never see the sky.", who: "Kiki", from: "Kiki's Delivery Service", tag: "Hope" },
  { q: "The strong live and the weak die.", who: "Yujiro Hanma", from: "Baki", tag: "Battle" },
  { q: "Reject common sense to make the impossible possible.", who: "Simon", from: "Gurren Lagann", tag: "Grit" },
  { q: "I'll keep moving forward until I have no legs to stand on.", who: "Asta", from: "Black Clover", tag: "Grit" },
  { q: "My magic is never giving up.", who: "Asta", from: "Black Clover", tag: "Grit" },
  { q: "I choose to keep living, even if it hurts.", who: "Rimuru Tempest", from: "That Time I Got Reincarnated as a Slime", tag: "Hope" },
  { q: "If you can't do something, then don't. Focus on what you can.", who: "Shiroe", from: "Log Horizon", tag: "Wisdom" },
  { q: "Being scared just means you have something to protect.", who: "Kirito", from: "Sword Art Online", tag: "Bonds" },
  { q: "There's no such thing as a painless lesson.", who: "Berserk narration", from: "Berserk", tag: "Wisdom" },
  { q: "A dream is not something you look at. It's something you reach.", who: "Rudeus Greyrat", from: "Mushoku Tensei", tag: "Hope" },
  { q: "The strongest weapon is knowing when not to fight.", who: "Thorfinn", from: "Vinland Saga", tag: "Wisdom" },
  { q: "I have no enemies.", who: "Thorfinn", from: "Vinland Saga", tag: "Wisdom" },
  { q: "Do you want to keep running, or do you want to fight?", who: "Isagi Yoichi", from: "Blue Lock", tag: "Sports" },
  { q: "Hunger is the greatest weapon a striker has.", who: "Jinpachi Ego", from: "Blue Lock", tag: "Sports" }
];

const QUOTE_TAGS = ['All', 'Grit', 'Wisdom', 'Bonds', 'Hope', 'Battle', 'Loss', 'Sports', 'Chaos'];
